FROM node:7.10

# Set the working directory to /app
WORKDIR /npm_pkgs

ADD ./package.json /npm_pkgs

# Install any needed packages specified in package.json
RUN npm install

WORKDIR /app

# Make port 3000 available to the world outside this container
EXPOSE 3000
